import { monthlyRate } from "./finance";

export type DcaInputs = { amount:number; waitingCash:number; dcaMonths:number; annualReturn:number; cashRate:number; dropPercent:number; dropMonth:number; years:number; essentialExpenses:number; emergencyMonths:number; plannedCashUse:number; stressTolerance:number };
type MarketScenario = { key:string; label:string; shockMonth:number | null };
function simulateStrategy(input:DcaInputs, shockMonth:number|null, lump:boolean) {
  const months=input.years*12; const growth=1+monthlyRate(input.annualReturn); const cashGrowth=1+monthlyRate(input.cashRate); let price=1; let units=lump?input.amount:0; let cash=lump?0:input.amount; let interest=0; let maxLoss=0; const tranche=input.amount/input.dcaMonths;
  for(let month=1;month<=months;month+=1){ price*=growth; if(shockMonth===month) price*=1-input.dropPercent/100; if(!lump&&month<=input.dcaMonths){ cash*=cashGrowth; interest+=cash*(cashGrowth-1); const buy=Math.min(tranche,cash); units+=buy/price; cash-=buy; } else if(!lump&&cash>0){ cash*=cashGrowth; interest+=cash*(cashGrowth-1); } const value=units*price+cash; const contributed=lump?input.amount:Math.min(month,input.dcaMonths)*tranche+cash; maxLoss=Math.max(maxLoss,Math.max(contributed-value,0)); }
  return { value:units*price+cash, interest, maxLoss, endingPrice:price };
}
export function calculateDcaComparison(input:DcaInputs){
  const scenarios:MarketScenario[]=[{key:"growth",label:"상승 지속",shockMonth:null},{key:"immediate",label:"투자 직후 급락",shockMonth:1},{key:"middle",label:"중간 급락 후 회복",shockMonth:Math.min(Math.max(input.dropMonth,2),input.years*12)}];
  const results=scenarios.map(s=>{const lump=simulateStrategy(input,s.shockMonth,true); const dca=simulateStrategy(input,s.shockMonth,false); return {...s,lump,dca,difference:lump.value-dca.value};});
  const growth=results[0]; const opportunityCost=Math.max(growth.lump.value-growth.dca.value,0); const reserve=input.waitingCash-input.plannedCashUse; const requiredReserve=input.essentialExpenses*input.emergencyMonths; const recoveryMonths=input.dropPercent<=0?0:input.annualReturn<=0?null:Math.ceil(Math.log(1/(1-input.dropPercent/100))/Math.log(1+monthlyRate(input.annualReturn))); const breakEvenAnnual=input.cashRate;
  let verdict="기대수익 우선: 일시투자 쪽이 적합"; if(reserve<requiredReserve) verdict="비상자금 부족: 목돈투자 부적합"; else if(input.plannedCashUse>0) verdict="현금 사용계획 존재: 투자 보류"; else if(input.stressTolerance<=2&&input.dropPercent>=10) verdict="손실 스트레스 우선: 3~6개월 분할";
  return {results,opportunityCost,reserve,requiredReserve,recoveryMonths,breakEvenAnnual,verdict,monthlyTranche:input.amount/input.dcaMonths};
}

export type RebalanceAsset={id:string;name:string;value:number;target:number;change:number;taxRate:number;category:string;leveraged:boolean;emergency:boolean};
export type RebalanceInputs={assets:RebalanceAsset[];newMoney:number;monthlyContribution:number;threshold:number;method:"new"|"exact"|"partial";feeRate:number;stressAssetId:string;stressDrop:number;reviewMonths:number};
export function calculateRebalancing(input:RebalanceInputs){
  const simulated=input.assets.map(a=>({...a,simulatedValue:a.value*(1+a.change/100)})); const currentTotal=simulated.reduce((s,a)=>s+a.simulatedValue,0); const finalTotal=currentTotal+input.newMoney; const targetSum=simulated.reduce((s,a)=>s+a.target,0); const current=simulated.map(a=>{const currentWeight=currentTotal?a.simulatedValue/currentTotal*100:0; const targetAmount=finalTotal*a.target/100; return {...a,currentWeight,deviation:currentWeight-a.target,targetAmount,exactAdjustment:targetAmount-a.simulatedValue};});
  const deficits=current.map(a=>Math.max(a.exactAdjustment,0)); const deficitSum=deficits.reduce((s,v)=>s+v,0); const newAlloc=current.map((a,i)=>deficitSum>0?input.newMoney*deficits[i]/deficitSum:input.newMoney*a.target/100);
  const partialRaw=current.map(a=>{const lower=Math.max(a.target-input.threshold,0)/100*finalTotal;const upper=Math.min(a.target+input.threshold,100)/100*finalTotal;if(a.simulatedValue<lower)return lower-a.simulatedValue;if(a.simulatedValue>upper)return upper-a.simulatedValue;return 0;});
  const partialBuyTotal=partialRaw.reduce((sum,value)=>sum+Math.max(value,0),0);
  const partialBuyScale=partialBuyTotal>input.newMoney&&partialBuyTotal>0?input.newMoney/partialBuyTotal:1;
  const rows=current.map((a,i)=>{let adjustment=0;if(input.method==="exact")adjustment=a.exactAdjustment;else if(input.method==="new")adjustment=newAlloc[i];else adjustment=partialRaw[i]>0?partialRaw[i]*partialBuyScale:partialRaw[i]; const postValue=a.simulatedValue+adjustment; const fee=Math.abs(adjustment)*input.feeRate/100; const tax=adjustment<0?Math.abs(adjustment)*a.taxRate/100:0; return {...a,newAllocation:newAlloc[i],adjustment,postValue,postWeight:finalTotal?postValue/finalTotal*100:0,fee,tax,action:adjustment>1?"매수":adjustment<-1?"매도":"유지"};});
  const over=[...current].sort((a,b)=>b.deviation-a.deviation)[0]; const under=[...current].sort((a,b)=>a.deviation-b.deviation)[0]; const maxDeviation=Math.max(...current.map(a=>Math.abs(a.deviation)),0); const relativeMax=Math.max(...current.map(a=>a.target?Math.abs(a.deviation)/a.target*100:0),0); const status=maxDeviation<3?"리밸런싱 불필요":maxDeviation<5&&relativeMax<20?"신규 투자금으로 조정":"리밸런싱 검토";
  const requiredNewMoney=Math.max(...current.filter(a=>a.deviation>input.threshold&&a.target+input.threshold>0).map(a=>a.simulatedValue/((a.target+input.threshold)/100)-currentTotal),0); const returnMonths=input.monthlyContribution>0?Math.ceil(requiredNewMoney/input.monthlyContribution):null; const totalFee=rows.reduce((s,a)=>s+a.fee,0); const totalTax=rows.reduce((s,a)=>s+a.tax,0); const shockAsset=simulated.find(a=>a.id===input.stressAssetId); const stressLoss=shockAsset&&currentTotal?shockAsset.simulatedValue*input.stressDrop/100:0; const stressPortfolioRate=currentTotal?stressLoss/currentTotal*100:0; const risks=[] as string[]; if(current.some(a=>a.currentWeight>50&&a.category!=="현금"))risks.push("단일 위험자산 50% 초과"); if(current.filter(a=>a.category==="암호화폐").reduce((s,a)=>s+a.currentWeight,0)>50)risks.push("암호화폐 비중 50% 초과"); if(current.some(a=>a.category==="개별주식"&&a.currentWeight>10))risks.push("개별주식 한 종목 10% 초과"); if(current.some(a=>a.leveraged))risks.push("레버리지 자산 포함"); if(current.some(a=>a.emergency))risks.push("비상자금이 투자자산에 포함됨");
  return {rows,currentTotal,finalTotal,targetSum,over,under,maxDeviation,relativeMax,status,requiredNewMoney,returnMonths,totalFee,totalTax,stressLoss,stressPortfolioRate,risks};
}
