"use client";
import { useMemo, useState } from "react";
import { CheckCircle2, ShieldAlert } from "lucide-react";
import { formatMoney, futureValue } from "../lib/finance";
import { LegalDisclaimer } from "./SiteChrome";

type Candidate = { name: string; initial: number; monthly: number; returnRate: number; worstLoss: number; cashflow: number; liquidity: number; taxRate: number; studyHours: number; leverage: number; evidence: number; exitClarity: number };
const defaults: Candidate[] = [
  { name: "주식·ETF", initial: 30_000_000, monthly: 500_000, returnRate: 7, worstLoss: 35, cashflow: 0, liquidity: 5, taxRate: 15.4, studyHours: 4, leverage: 0, evidence: 4, exitClarity: 4 },
  { name: "부동산·부업 등 투자안", initial: 30_000_000, monthly: 0, returnRate: 5, worstLoss: 20, cashflow: 300_000, liquidity: 2, taxRate: 15.4, studyHours: 12, leverage: 50, evidence: 3, exitClarity: 3 },
  { name: "아무것도 하지 않기", initial: 30_000_000, monthly: 0, returnRate: 2.5, worstLoss: 0, cashflow: 0, liquidity: 5, taxRate: 15.4, studyHours: 0, leverage: 0, evidence: 5, exitClarity: 5 },
];
function Field({ label, value, onChange, unit = "원", min = 0, max = 10_000_000_000 }: { label: string; value: number; onChange: (v: number) => void; unit?: string; min?: number; max?: number }) { return <label className="field"><span className="field-label">{label}</span><span className="input-wrap"><input value={unit === "원" ? Math.round(value).toLocaleString("ko-KR") : value} onChange={(e) => { const raw = e.target.value.replace(min < 0 ? /[^0-9.-]/g : /[^0-9.]/g, ""); onChange(Math.min(Math.max(Number(raw) || 0, min), max)); }} /><span>{unit}</span></span></label>; }
export function InvestmentCompareCalculator() {
  const [items, setItems] = useState(defaults); const [years, setYears] = useState(10);
  const update = (index: number, patch: Partial<Candidate>) => setItems((current) => current.map((item, i) => i === index ? { ...item, ...patch } : item));
  const results = useMemo(() => items.map((item) => {
    const gross = futureValue(item.initial, item.monthly + item.cashflow, item.returnRate, years * 12); const principal = item.initial + (item.monthly + item.cashflow) * years * 12; const tax = Math.max(gross - principal, 0) * item.taxRate / 100; const afterTax = gross - tax; const lossAmount = item.initial * item.worstLoss / 100; const paybackMonths = item.cashflow > 0 ? Math.ceil(item.initial / item.cashflow) : null;
    const returnScore = Math.max(0, Math.min(100, (item.returnRate + 5) / 20 * 100)); const safetyScore = 100 - item.worstLoss; const cashScore = paybackMonths ? Math.max(0, 100 - paybackMonths / 2.4) : item.name.includes("아무것도") ? 60 : 35; const liquidityScore = item.liquidity * 20; const taxScore = 100 - item.taxRate; const studyScore = Math.max(0, 100 - item.studyHours * 3); const leverageScore = 100 - item.leverage;
    const quantitative = returnScore * .25 + safetyScore * .2 + cashScore * .15 + liquidityScore * .12 + taxScore * .08 + studyScore * .1 + leverageScore * .1; const qualitative = (item.evidence + item.exitClarity) / 10 * 100; const total = quantitative * .7 + qualitative * .3;
    return { ...item, gross, afterTax, tax, lossAmount, paybackMonths, quantitative, qualitative, total };
  }).sort((a, b) => b.total - a.total), [items, years]);
  return <div className="comparison-lab"><section className="input-panel"><div className="panel-heading"><div><span>STEP 01 · OPTIONS</span><h2>최대 세 가지 투자안을 같은 기준으로 입력해 주세요</h2></div></div><div className="field-grid"><Field label="비교 기간" value={years} onChange={setYears} unit="년" min={1} max={30} /></div><div className="compare-columns">{items.map((item, index) => <div className="compare-option" key={index}><input className="option-name" value={item.name} onChange={(e) => update(index, { name: e.target.value })} aria-label={`${index + 1}번 투자안 이름`} /><Field label="초기 투입금" value={item.initial} onChange={(v) => update(index, { initial: v })} /><Field label="월 추가 투자" value={item.monthly} onChange={(v) => update(index, { monthly: v })} /><Field label="연 기대수익률" value={item.returnRate} onChange={(v) => update(index, { returnRate: v })} unit="%" min={-30} max={50} /><Field label="최악의 손실" value={item.worstLoss} onChange={(v) => update(index, { worstLoss: v })} unit="%" max={100} /><Field label="월 순현금흐름" value={item.cashflow} onChange={(v) => update(index, { cashflow: v })} /><Field label="현금화 용이성" value={item.liquidity} onChange={(v) => update(index, { liquidity: v })} unit="/ 5" min={1} max={5} /><Field label="수익 과세율" value={item.taxRate} onChange={(v) => update(index, { taxRate: v })} unit="%" max={60} /><Field label="월 필요 공부시간" value={item.studyHours} onChange={(v) => update(index, { studyHours: v })} unit="시간" max={100} /><Field label="레버리지 비율" value={item.leverage} onChange={(v) => update(index, { leverage: v })} unit="%" max={100} /><Field label="투자 근거의 강도" value={item.evidence} onChange={(v) => update(index, { evidence: v })} unit="/ 5" min={1} max={5} /><Field label="매도·철수 기준 명확성" value={item.exitClarity} onChange={(v) => update(index, { exitClarity: v })} unit="/ 5" min={1} max={5} /></div>)}</div></section><section className="result-panel"><div className="panel-heading"><div><span>STEP 02 · FIT SCORE</span><h2>내 상황에 맞는 투자안 순위</h2></div></div><div className="verdict-line"><span>종합점수 1순위</span><strong className="verdict">{results[0].name}</strong><p>정량점수 70%와 투자 근거·철수 기준의 정성점수 30%를 합산했습니다.</p></div><div className="candidate-results">{results.map((item, index) => <article key={item.name} className="candidate-result"><div><span>{index + 1}위</span><h3>{item.name}</h3>{index === 0 && <CheckCircle2 size={18} />}</div><strong>{item.total.toFixed(1)}점</strong><dl><div><dt>{years}년 세후 예상자산</dt><dd>{formatMoney(item.afterTax)}</dd></div><div><dt>최악의 손실액</dt><dd>−{formatMoney(item.lossAmount)}</dd></div><div><dt>원금 회수기간</dt><dd>{item.paybackMonths ? `${Math.ceil(item.paybackMonths / 12)}년` : "현금흐름만으로 회수 불가"}</dd></div><div><dt>정량 / 정성</dt><dd>{item.quantitative.toFixed(0)} / {item.qualitative.toFixed(0)}</dd></div></dl></article>)}</div><div className="warning-strip"><ShieldAlert size={17} /><span>점수는 선택을 대신하지 않습니다. 특히 레버리지, 세금과 최악의 손실은 실제 상품 구조에 맞게 보수적으로 입력해 주세요.</span></div><LegalDisclaimer /></section></div>;
}
