"use client";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Check, Download, FileText, Save, Target, Trash2 } from "lucide-react";
import { formatMoney, futureValue, monthlyLoanPayment, recurringFutureValue } from "../lib/finance";
import { EditableNumberInput, sanitizeNumericDraft } from "./EditableNumberInput";
import { InputModeSwitch, QuickAssumptionNote, QuickEstimateNotice, type InputMode } from "./InputModeSwitch";
import { LegalDisclaimer } from "./SiteChrome";

function Field({ label, value, onChange, unit = "원", min = 0, max = 10_000_000_000 }: { label: string; value: number; onChange: (v: number) => void; unit?: string; min?: number; max?: number }) { const money = unit === "원"; return <label className="field"><span className="field-label">{label}</span><span className="input-wrap"><EditableNumberInput value={value} onValueChange={onChange} min={min} max={max} decimalPlaces={money || unit === "년" ? 0 : 2} format={money ? "money" : "plain"} aria-label={label} /><span>{unit}</span></span></label>; }
function TextField({ label, value, onChange, hint }: { label: string; value: string; onChange: (v: string) => void; hint?: string }) { return <label className="note-field"><span>{label}</span><textarea value={value} maxLength={10_000} onChange={(e) => onChange(e.target.value)} placeholder={hint} rows={3} /></label>; }

type Metric = number | null;
type Journal = {
  id: string; investmentName: string; ticker: string; market: string; industry: string; decision: string; decisionDate: string; reviewDate: string; moatType: string;
  currentPrice: Metric; entryPrice: Metric; shares: Metric; amount: Metric; marketCap: Metric; portfolioWeight: Metric; holdingMonths: Metric;
  per: Metric; industryPer: Metric; forwardPer: Metric; pbr: Metric; evEbitda: Metric; fcfYield: Metric; dividendYield: Metric;
  revenueOld: Metric; revenueMid: Metric; revenueRecent: Metric; operatingProfitOld: Metric; operatingProfitMid: Metric; operatingProfitRecent: Metric;
  netIncome: Metric; operatingCashFlow: Metric; capex: Metric; roe: Metric; roic: Metric; debtRatio: Metric; netDebtEbitda: Metric; interestCoverage: Metric;
  expectedReturn: Metric; worstLoss: Metric; probability: Metric; estimatedValue: Metric;
  thesis: string; invalidation: string; keyRisk: string; sellCondition: string; sources: string;
  actualReturn: Metric; actualResult: string; rulesKept: Metric; lesson: string;
};
const today = () => {
  const date = new Date();
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
};
const journalDefaults: Journal = {
  id: "", investmentName: "", ticker: "", market: "한국", industry: "", decision: "매수 검토", decisionDate: today(), reviewDate: "", moatType: "아직 판단하지 않음",
  currentPrice: null, entryPrice: null, shares: null, amount: null, marketCap: null, portfolioWeight: null, holdingMonths: 36,
  per: null, industryPer: null, forwardPer: null, pbr: null, evEbitda: null, fcfYield: null, dividendYield: null,
  revenueOld: null, revenueMid: null, revenueRecent: null, operatingProfitOld: null, operatingProfitMid: null, operatingProfitRecent: null,
  netIncome: null, operatingCashFlow: null, capex: null, roe: null, roic: null, debtRatio: null, netDebtEbitda: null, interestCoverage: null,
  expectedReturn: 10, worstLoss: 30, probability: 60, estimatedValue: null,
  thesis: "", invalidation: "", keyRisk: "", sellCondition: "", sources: "",
  actualReturn: null, actualResult: "", rulesKept: null, lesson: "",
};
function NullableNumberInput({ value, onChange, min, max, integer, label }: { value: Metric; onChange: (value: Metric) => void; min: number; max: number; integer: boolean; label: string }) {
  const [draft, setDraft] = useState<string | null>(null);
  const shown = draft ?? (value === null ? "" : String(value));
  return <input inputMode={integer ? "numeric" : "decimal"} value={shown} placeholder="미입력" aria-label={label} onFocus={() => setDraft(value === null ? "" : String(value))} onBlur={() => setDraft(null)} onChange={event => {
    const next = sanitizeNumericDraft(event.target.value, min < 0, integer ? 0 : 2);
    setDraft(next);
    if (next === "" || next === "-" || next === "." || next === "-.") { onChange(null); return; }
    const parsed = Number(next);
    if (Number.isFinite(parsed)) onChange(Math.min(Math.max(parsed, min), max));
  }} />;
}
function MetricField({label,value,onChange,unit="배",min=-1_000_000_000,max=1_000_000_000_000_000,hint}:{label:string;value:Metric;onChange:(v:Metric)=>void;unit?:string;min?:number;max?:number;hint?:string}){const integer=unit==="원"||unit==="주"||unit==="개월";return <label className="field metric-field"><span className="field-label">{label}</span><span className="input-wrap"><NullableNumberInput value={value} onChange={onChange} min={min} max={max} integer={integer} label={label}/><span>{unit}</span></span>{hint&&<small>{hint}</small>}</label>}
function ShortText({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="field"><span className="field-label">{label}</span><span className="input-wrap text-input"><input type={type} value={value} maxLength={type === "date" ? undefined : 200} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></span></label>}
function JournalSelect({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="field"><span className="field-label">{label}</span><span className="select-wrap"><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></span></label>}
const present=(value:Metric):value is number=>value!==null&&Number.isFinite(value);
const ratio=(numerator:Metric,denominator:Metric)=>present(numerator)&&present(denominator)&&denominator!==0?numerator/denominator*100:null;
const cagr=(start:Metric,end:Metric,years:number)=>present(start)&&present(end)&&start>0&&end>0?(Math.pow(end/start,1/years)-1)*100:null;
const metricText=(value:Metric,unit="%",digits=1)=>present(value)?`${value.toFixed(digits)}${unit}`:"—";
const masters = [
  { name: "사업 지속성", principle: "경제성과 현금흐름", note: "한 문장 투자논지와 경쟁우위 유형만 남기고, 실제 수익성은 영업이익률·ROIC·현금흐름으로 확인합니다." },
  { name: "가격·가치 점검", principle: "비교 기준과 안전마진", note: "적정가 대비 안전마진과 업종 PER 대비 할인·프리미엄을 숫자로 기록합니다." },
  { name: "논지·실적 점검", principle: "설명과 숫자의 일치", note: "3개년 매출·영업이익·마진 추세가 투자논지를 뒷받침하는지 확인합니다." },
  { name: "위험 점검", principle: "반증과 손실 통제", note: "논지가 깨지는 조건, 최대손실, 확률과 포트폴리오 비중만 필수 정성·위험 항목으로 남깁니다." },
];
const JOURNAL_STORAGE_KEY = "wdl-investment-journal";
const JOURNAL_CONSENT_KEY = `${JOURNAL_STORAGE_KEY}:enabled`;
const JOURNAL_TTL_MS = 90 * 24 * 60 * 60 * 1_000;
const MAX_JOURNAL_RECORDS = 200;

function normalizeJournal(value: unknown): Journal | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const source = value as Record<string, unknown>;
  const normalized = { ...journalDefaults } as Journal;
  for (const key of Object.keys(journalDefaults) as Array<keyof Journal>) {
    const fallback = journalDefaults[key];
    const candidate = source[key];
    if (fallback === null) {
      if (candidate === null || candidate === undefined || candidate === "") (normalized as Record<string, unknown>)[key] = null;
      else if (typeof candidate === "number" && Number.isFinite(candidate) && Math.abs(candidate) <= 1_000_000_000_000_000) (normalized as Record<string, unknown>)[key] = candidate;
      else return null;
    } else if (typeof fallback === "string") {
      if (typeof candidate === "string") (normalized as Record<string, unknown>)[key] = candidate.slice(0, 10_000);
      else if (candidate !== undefined) return null;
    } else if (typeof fallback === "number") {
      if (typeof candidate === "number" && Number.isFinite(candidate) && Math.abs(candidate) <= 1_000_000_000_000_000) (normalized as Record<string, unknown>)[key] = candidate;
      else if (candidate !== undefined) return null;
    }
  }
  return normalized;
}

function parseJournalEnvelope(raw: string): { records: Journal[]; expired: boolean } {
  const parsed = JSON.parse(raw) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("invalid journal envelope");
  const envelope = parsed as { expiresAt?: unknown; records?: unknown };
  if (typeof envelope.expiresAt !== "number" || !Number.isFinite(envelope.expiresAt)) throw new Error("missing expiry");
  if (envelope.expiresAt <= Date.now()) return { records: [], expired: true };
  if (!Array.isArray(envelope.records) || envelope.records.length > MAX_JOURNAL_RECORDS) throw new Error("invalid record list");
  const records = envelope.records.map(normalizeJournal);
  if (records.some(record => record === null)) throw new Error("invalid record");
  return { records: records as Journal[], expired: false };
}

export function DecisionJournal() {
  const [input,setInput]=useState<Journal>(journalDefaults); const [inputMode,setInputMode]=useState<InputMode>("quick"); const [records,setRecords]=useState<Journal[]>([]); const [saved,setSaved]=useState(false); const [storageConsent,setStorageConsent]=useState(false); const [storageMessage,setStorageMessage]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const consent=localStorage.getItem(JOURNAL_CONSENT_KEY)==="true";setStorageConsent(consent);if(!consent){localStorage.removeItem(JOURNAL_STORAGE_KEY);return}const value=localStorage.getItem(JOURNAL_STORAGE_KEY);if(value){const parsed=parseJournalEnvelope(value);if(parsed.expired){localStorage.removeItem(JOURNAL_STORAGE_KEY);localStorage.removeItem(JOURNAL_CONSENT_KEY);setStorageConsent(false);setStorageMessage("90일 보관기간이 지나 저장된 기록을 삭제했습니다.")}else setRecords(parsed.records)}}catch{try{localStorage.removeItem(JOURNAL_STORAGE_KEY);localStorage.removeItem(JOURNAL_CONSENT_KEY)}catch{/* 브라우저 저장소가 완전히 차단된 경우 */}setStorageConsent(false);setStorageMessage("브라우저 저장소를 사용할 수 없어 기기 저장을 껐습니다. JSON 내려받기를 이용해 주세요.")}},0);return()=>window.clearTimeout(timer)},[]);
  const update=<K extends keyof Journal>(key:K,value:Journal[K])=>setInput(current=>({...current,[key]:value}));
  const margins=[ratio(input.operatingProfitOld,input.revenueOld),ratio(input.operatingProfitMid,input.revenueMid),ratio(input.operatingProfitRecent,input.revenueRecent)];
  const revenueCagr=cagr(input.revenueOld,input.revenueRecent,2); const operatingProfitCagr=cagr(input.operatingProfitOld,input.operatingProfitRecent,2);
  const marginTrend=present(margins[0])&&present(margins[2])?margins[2]-margins[0]:null;
  const perGap=present(input.per)&&present(input.industryPer)&&input.industryPer!==0?(input.per/input.industryPer-1)*100:null;
  const cashConversion=present(input.netIncome)&&input.netIncome>0?ratio(input.operatingCashFlow,input.netIncome):null; const freeCashFlow=present(input.operatingCashFlow)&&present(input.capex)?input.operatingCashFlow-input.capex:null;
  const referencePrice=present(input.entryPrice)?input.entryPrice:input.currentPrice; const safetyMargin=present(input.estimatedValue)&&present(referencePrice)&&input.estimatedValue!==0?(input.estimatedValue-referencePrice)/input.estimatedValue*100:null;
  const checks=[
    {label:"업종 PER 이하",value:present(input.per)&&present(input.industryPer)&&input.per>0&&input.industryPer>0?input.per<=input.industryPer:null,detail:present(perGap)?`업종 대비 ${Math.abs(perGap).toFixed(1)}% ${perGap<=0?"할인":"프리미엄"}`:"흑자기업의 동일 기준 PER 입력 필요"},
    {label:"선행 PER 개선",value:present(input.per)&&present(input.forwardPer)&&input.per>0&&input.forwardPer>0?input.forwardPer<=input.per:null,detail:"선행 PER이 현재 PER 이하인지 확인"},
    {label:"3개년 매출 성장",value:present(revenueCagr)?revenueCagr>=0:null,detail:`CAGR ${metricText(revenueCagr)}`},
    {label:"영업이익률 유지·개선",value:present(marginTrend)?marginTrend>=0:null,detail:`3개년 변화 ${metricText(marginTrend,"%p")}`},
    {label:"ROIC가 요구수익률 이상",value:present(input.roic)&&present(input.expectedReturn)?input.roic>=input.expectedReturn:null,detail:`ROIC ${metricText(input.roic)} · 요구 ${metricText(input.expectedReturn)}`},
    {label:"현금전환율 80% 이상",value:present(cashConversion)?cashConversion>=80:null,detail:`영업현금흐름 ÷ 순이익 ${metricText(cashConversion)}`},
    {label:"잉여현금흐름 흑자",value:present(freeCashFlow)?freeCashFlow>=0:null,detail:`영업현금흐름 − CAPEX ${present(freeCashFlow)?freeCashFlow.toLocaleString("ko-KR")+"억원":"—"}`},
    {label:"부채비율 200% 이하",value:present(input.debtRatio)?input.debtRatio<=200:null,detail:`현재 ${metricText(input.debtRatio)}`},
    {label:"순차입금/EBITDA 3배 이하",value:present(input.netDebtEbitda)?input.netDebtEbitda<=3:null,detail:`현재 ${metricText(input.netDebtEbitda,"배")}`},
    {label:"이자보상배율 3배 이상",value:present(input.interestCoverage)?input.interestCoverage>=3:null,detail:`현재 ${metricText(input.interestCoverage,"배")}`},
  ];
  const availableChecks=checks.filter(check=>check.value!==null); const passedChecks=availableChecks.filter(check=>check.value).length; const failedChecks=availableChecks.length-passedChecks;
  const completenessValues=[input.investmentName,input.ticker,input.industry,input.currentPrice,input.per,input.industryPer,input.revenueOld,input.revenueMid,input.revenueRecent,input.operatingProfitOld,input.operatingProfitMid,input.operatingProfitRecent,input.roic,input.debtRatio,input.operatingCashFlow,input.netIncome,input.thesis,input.invalidation,input.sellCondition,input.sources];
  const completeness=Math.round(completenessValues.filter(value=>typeof value==="string"?value.trim().length>0:present(value)).length/completenessValues.length*100);
  const status=completeness<60?"기초 데이터 입력 중":failedChecks>=4?"위험 신호 우선 점검":"정량 검토 완료";
  const persist=(next:Journal[])=>{const limited=next.slice(0,MAX_JOURNAL_RECORDS);if(!storageConsent)return false;try{localStorage.setItem(JOURNAL_STORAGE_KEY,JSON.stringify({version:1,expiresAt:Date.now()+JOURNAL_TTL_MS,records:limited}));setRecords(limited);return true}catch{setStorageMessage("브라우저 저장 공간이 차단되었거나 부족합니다. JSON 내려받기를 이용해 주세요.");return false}};
  const save=()=>{if(!storageConsent){setStorageMessage("먼저 기기 저장 동의에 체크해 주세요.");return}const record={...input,id:input.id||`${Date.now()}`};const next=input.id?records.map(item=>item.id===input.id?record:item):[record,...records];if(!persist(next))return;setInput(record);setStorageMessage("");setSaved(true);setTimeout(()=>setSaved(false),1500)};
  const download=()=>{const payload={version:1,exportedAt:new Date().toISOString(),guide:"기업가치·3개년 실적·현금흐름 중심의 주식 투자 기록",records:records.length?records:[input]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=`stock-investment-journal-${today()}.json`;anchor.click();URL.revokeObjectURL(anchor.href)};
  const changeStorageConsent=(enabled:boolean)=>{setStorageMessage("");try{if(enabled){localStorage.setItem(JOURNAL_STORAGE_KEY,JSON.stringify({version:1,expiresAt:Date.now()+JOURNAL_TTL_MS,records}));localStorage.setItem(JOURNAL_CONSENT_KEY,"true");setStorageConsent(true)}else{localStorage.removeItem(JOURNAL_CONSENT_KEY);localStorage.removeItem(JOURNAL_STORAGE_KEY);setStorageConsent(false);setRecords([])}}catch{try{localStorage.removeItem(JOURNAL_CONSENT_KEY);localStorage.removeItem(JOURNAL_STORAGE_KEY)}catch{/* 저장소가 완전히 차단된 경우 */}setStorageConsent(false);setStorageMessage("브라우저 저장소를 사용할 수 없어 동의를 저장하지 못했습니다. JSON 내려받기를 이용해 주세요.")}};
  const clearAll=()=>{setRecords([]);try{localStorage.removeItem(JOURNAL_STORAGE_KEY);setStorageMessage("이 기기에 저장된 투자 기록을 모두 삭제했습니다.")}catch{setStorageMessage("화면의 기록은 지웠지만 브라우저 저장소 삭제를 확인하지 못했습니다. 브라우저 사이트 데이터에서도 삭제해 주세요.")}};
  const openBacktest=()=>{try{sessionStorage.setItem("wdl-backtest-screening",JSON.stringify({requiredReturn:input.expectedReturn??10,minimumPass:Math.max(Math.min(passedChecks||7,10),1),minimumValid:Math.max(Math.min(availableChecks.length||7,10),1)}))}catch{setStorageMessage("브라우저 저장소가 차단되어 기준을 전달하지 못했습니다. 백테스트에서 직접 입력해 주세요.")}window.location.assign("/invest/quant-backtest")};
  return <div className="journal-layout"><section className="input-panel"><div className="panel-heading"><div><span>QUANTITATIVE INVESTMENT JOURNAL</span><h2>주식의 매수 이유는 기록해야 합니다.</h2></div></div>
    <div className="journal-notice"><strong>입력·개인정보 원칙</strong><span>같은 회계기준·같은 기간의 연결재무제표를 사용하세요. 금융회사·리츠·유틸리티는 공통 판정을 그대로 적용하기 어렵습니다. 투자 기록은 민감정보가 될 수 있어 이 화면에는 광고 슬롯을 두지 않습니다.</span></div>
    <InputModeSwitch mode={inputMode} onChange={setInputMode} quickDescription="종목·매수 계획·기대수익과 손실·투자 이유만 먼저 기록합니다. 재무제표 점검은 나중에 추가할 수 있습니다." />
    <div className="field-section"><h3>1. 종목과 매수 계획</h3><div className="field-grid"><ShortText label="기업명" value={input.investmentName} onChange={v=>update("investmentName",v)} placeholder="예: 삼성전자"/><ShortText label="티커·종목코드" value={input.ticker} onChange={v=>update("ticker",v)} placeholder="예: 005930"/>{inputMode === "detailed" && <><ShortText label="시장" value={input.market} onChange={v=>update("market",v)} placeholder="한국·미국"/><ShortText label="산업·업종" value={input.industry} onChange={v=>update("industry",v)} placeholder="동일 비교군 기준"/></>}<JournalSelect label="현재 결정" value={input.decision} onChange={v=>update("decision",v)}><option>매수 검토</option><option>보유 점검</option><option>추가매수 검토</option><option>매도 검토</option></JournalSelect>{inputMode === "detailed" && <JournalSelect label="경쟁우위 유형" value={input.moatType} onChange={v=>update("moatType",v)}><option>아직 판단하지 않음</option><option>브랜드·가격결정력</option><option>네트워크 효과</option><option>전환비용</option><option>원가우위</option><option>규모의 경제</option><option>규제·특허</option><option>뚜렷한 우위 없음</option></JournalSelect>}<ShortText label="결정일" type="date" value={input.decisionDate} onChange={v=>update("decisionDate",v)}/>{inputMode === "detailed" && <ShortText label="다음 점검일" type="date" value={input.reviewDate} onChange={v=>update("reviewDate",v)}/>}</div><div className="field-grid"><MetricField label="현재 주가" value={input.currentPrice} onChange={v=>update("currentPrice",v)} unit="원"/><MetricField label="검토 매수가" value={input.entryPrice} onChange={v=>update("entryPrice",v)} unit="원"/>{inputMode === "detailed" && <MetricField label="매수 수량" value={input.shares} onChange={v=>update("shares",v)} unit="주"/>}<MetricField label="투자 예정액" value={input.amount} onChange={v=>update("amount",v)} unit="원"/>{inputMode === "detailed" && <MetricField label="시가총액" value={input.marketCap} onChange={v=>update("marketCap",v)} unit="억원"/>}<MetricField label="투자 후 비중" value={input.portfolioWeight} onChange={v=>update("portfolioWeight",v)} unit="%" min={0} max={100}/><MetricField label="예상 보유기간" value={input.holdingMonths} onChange={v=>update("holdingMonths",v)} unit="개월" min={1} max={600}/></div></div>
    {inputMode === "detailed" && <><div className="field-section valuation-section"><h3>2. 상대가치와 시장 기대</h3><p className="section-help">기업과 업종은 같은 기준의 후행 PER을 사용하고, 적자기업은 PER 비교 대신 매출·현금흐름과 손익분기 시점을 별도로 확인하세요.</p><div className="field-grid"><MetricField label="기업 PER" value={input.per} onChange={v=>update("per",v)}/><MetricField label="동일 산업 PER" value={input.industryPer} onChange={v=>update("industryPer",v)} hint="국가·업종·시점이 같은 비교군"/><MetricField label="선행 PER" value={input.forwardPer} onChange={v=>update("forwardPer",v)}/><MetricField label="PBR" value={input.pbr} onChange={v=>update("pbr",v)}/><MetricField label="EV/EBITDA" value={input.evEbitda} onChange={v=>update("evEbitda",v)}/><MetricField label="FCF 수익률" value={input.fcfYield} onChange={v=>update("fcfYield",v)} unit="%"/><MetricField label="배당수익률" value={input.dividendYield} onChange={v=>update("dividendYield",v)} unit="%"/><MetricField label="적정가·내재가치" value={input.estimatedValue} onChange={v=>update("estimatedValue",v)} unit="원"/></div></div>
    <div className="field-section"><h3>3. 3개년 매출·영업이익</h3><p className="section-help">전전년부터 최근연도까지 같은 단위로 입력하면 영업이익률과 연평균성장률을 자동 계산합니다.</p><div className="financial-years"><article><span>전전년 · Y-2</span><MetricField label="매출" value={input.revenueOld} onChange={v=>update("revenueOld",v)} unit="억원"/><MetricField label="영업이익" value={input.operatingProfitOld} onChange={v=>update("operatingProfitOld",v)} unit="억원"/><strong>영업이익률 {metricText(margins[0])}</strong></article><article><span>전년 · Y-1</span><MetricField label="매출" value={input.revenueMid} onChange={v=>update("revenueMid",v)} unit="억원"/><MetricField label="영업이익" value={input.operatingProfitMid} onChange={v=>update("operatingProfitMid",v)} unit="억원"/><strong>영업이익률 {metricText(margins[1])}</strong></article><article><span>최근연도 · Y0</span><MetricField label="매출" value={input.revenueRecent} onChange={v=>update("revenueRecent",v)} unit="억원"/><MetricField label="영업이익" value={input.operatingProfitRecent} onChange={v=>update("operatingProfitRecent",v)} unit="억원"/><strong>영업이익률 {metricText(margins[2])}</strong></article></div><div className="derived-strip"><div><span>매출 CAGR</span><strong>{metricText(revenueCagr)}</strong></div><div><span>영업이익 CAGR</span><strong>{metricText(operatingProfitCagr)}</strong></div><div><span>영업이익률 변화</span><strong>{metricText(marginTrend,"%p")}</strong></div></div></div>
    <div className="field-section"><h3>4. 수익성·현금흐름·재무안전성</h3><div className="field-grid"><MetricField label="ROE" value={input.roe} onChange={v=>update("roe",v)} unit="%"/><MetricField label="ROIC" value={input.roic} onChange={v=>update("roic",v)} unit="%"/><MetricField label="최근 순이익" value={input.netIncome} onChange={v=>update("netIncome",v)} unit="억원"/><MetricField label="최근 영업현금흐름" value={input.operatingCashFlow} onChange={v=>update("operatingCashFlow",v)} unit="억원"/><MetricField label="최근 CAPEX" value={input.capex} onChange={v=>update("capex",v)} unit="억원"/><MetricField label="부채비율" value={input.debtRatio} onChange={v=>update("debtRatio",v)} unit="%"/><MetricField label="순차입금/EBITDA" value={input.netDebtEbitda} onChange={v=>update("netDebtEbitda",v)}/><MetricField label="이자보상배율" value={input.interestCoverage} onChange={v=>update("interestCoverage",v)}/></div><div className="derived-strip"><div><span>현금전환율</span><strong>{metricText(cashConversion)}</strong></div><div><span>추정 FCF</span><strong>{present(freeCashFlow)?freeCashFlow.toLocaleString("ko-KR")+"억원":"—"}</strong></div><div><span>안전마진</span><strong>{metricText(safetyMargin)}</strong></div></div></div></>}
    <div className="field-section"><h3>5. 기대수익과 손실 계획</h3><div className="field-grid"><MetricField label="요구·기대수익률" value={input.expectedReturn} onChange={v=>update("expectedReturn",v)} unit="%" min={-100} max={500}/><MetricField label="예상 최대손실" value={input.worstLoss} onChange={v=>update("worstLoss",v)} unit="%" min={0} max={100}/><MetricField label="논지 실현 확률" value={input.probability} onChange={v=>update("probability",v)} unit="%" min={0} max={100}/></div></div>
    <div className="field-section qualitative-core"><h3>6. 숫자로 대체할 수 없는 필수 기록</h3><p className="section-help">설명문은 다섯 칸만 남겼습니다. 수치가 왜 지속될지와 어떤 조건에서 판단을 바꿀지만 짧게 기록하세요.</p><div className="note-grid"><TextField label="한 문장 투자논지" value={input.thesis} onChange={v=>update("thesis",v)} hint="무엇이 언제까지 기업가치를 높인다고 보는지 한 문장으로 적어 주세요."/><TextField label="논지가 깨지는 조건" value={input.invalidation} onChange={v=>update("invalidation",v)} hint="수치와 기한을 포함하면 좋습니다."/><TextField label="가장 큰 비정량 위험" value={input.keyRisk} onChange={v=>update("keyRisk",v)} hint="규제, 지배구조, 기술 대체 등 숫자에 아직 드러나지 않은 위험"/><TextField label="매도·축소 조건" value={input.sellCondition} onChange={v=>update("sellCondition",v)} hint="가격이 아니라 논지·밸류에이션·비중 기준으로 적어 주세요."/><TextField label="재무제표·산업 비교 출처" value={input.sources} onChange={v=>update("sources",v)} hint="사업보고서 기준일, 데이터 URL, 업종 비교군을 기록해 주세요."/></div></div>
    {inputMode === "detailed" && <div className="field-section"><h3>7. 투자 후 복기</h3><div className="field-grid"><MetricField label="실제 수익률" value={input.actualReturn} onChange={v=>update("actualReturn",v)} unit="%" min={-100} max={1000}/><MetricField label="사전 규칙 준수" value={input.rulesKept} onChange={v=>update("rulesKept",v)} unit="/ 5" min={1} max={5}/></div><div className="note-grid"><TextField label="실제 결과와 예상의 차이" value={input.actualResult} onChange={v=>update("actualResult",v)}/><TextField label="다음 투자에 반영할 한 가지" value={input.lesson} onChange={v=>update("lesson",v)}/></div></div>}
    <QuickAssumptionNote mode={inputMode}>재무지표는 비워 둔 채 ‘기초 기록’으로 저장합니다. 정량 점검을 받으려면 상세 기록에서 공시자료를 확인해 채워 주세요.</QuickAssumptionNote>
    <div className="privacy-note"><label><input type="checkbox" checked={storageConsent} onChange={event=>changeStorageConsent(event.target.checked)}/> 투자 판단 기록을 이 기기에 최대 90일간 저장하는 데 동의합니다.</label><small>동의를 해제하면 이 기기에 저장된 기록을 즉시 삭제합니다. JSON 내려받기는 기기에 파일을 저장하는 별도 동작입니다.</small></div>{storageMessage&&<p className="inline-message" role="status">{storageMessage}</p>}
    <div className="result-actions journal-actions"><button className="primary-button" type="button" disabled={!storageConsent} onClick={save}>{saved?<Check size={17}/>:<Save size={17}/>} {saved?"저장되었습니다":"투자 기록 저장"}</button><button className="secondary-button" type="button" onClick={download}><Download size={17}/> 전체 기록 JSON</button><button className="secondary-button" type="button" disabled={records.length===0} onClick={clearAll}><Trash2 size={17}/> 저장 기록 전체 삭제</button><button className="secondary-button backtest-link-button" type="button" onClick={openBacktest}><BarChart3 size={17}/> 이 기준으로 백테스트하기</button></div></section>
    <aside className="result-panel journal-side"><QuickEstimateNotice mode={inputMode} label="빠른 기록 상태" /><div className="verdict-line"><span>정량 점검 상태</span><strong className="verdict">{status}</strong><p>매수 추천 점수가 아니라 입력 완성도와 공개 기준의 주의 항목을 보여줍니다.</p></div><div className="kpi-grid"><div className="kpi"><span>필수 데이터 완성도</span><strong>{completeness}%</strong></div><div className="kpi"><span>정량 기준 통과</span><strong>{passedChecks} / {availableChecks.length}</strong></div><div className="kpi"><span>주의 항목</span><strong>{failedChecks}개</strong></div></div><div className="journal-metrics"><div><span>업종 대비 PER</span><strong>{present(perGap)?`${Math.abs(perGap).toFixed(1)}% ${perGap<=0?"할인":"프리미엄"}`:"—"}</strong></div><div><span>3개년 매출 CAGR</span><strong>{metricText(revenueCagr)}</strong></div><div><span>영업이익률 변화</span><strong>{metricText(marginTrend,"%p")}</strong></div><div><span>현금전환율</span><strong>{metricText(cashConversion)}</strong></div></div><div className="quant-checks"><h3>공개된 정량 점검 규칙</h3>{checks.map(check=><div className={check.value===null?"is-empty":check.value?"is-pass":"is-warn"} key={check.label}><b>{check.value===null?"—":check.value?"통과":"주의"}</b><span>{check.label}<small>{check.detail}</small></span></div>)}</div><div className="master-checklist"><h3>보조 점검 관점</h3>{masters.map(master=><details key={master.name}><summary>{master.name} · {master.principle}</summary><p>{master.note}</p></details>)}</div><div className="saved-records"><h3>이 브라우저에 저장된 기록</h3>{records.length===0?<p>아직 저장된 기록이 없습니다.</p>:records.map(record=><div key={record.id}><button type="button" onClick={()=>setInput({...journalDefaults,...record})}><FileText size={15}/><span>{record.investmentName||"이름 없는 종목"}<small>{record.ticker||"티커 미입력"} · {record.decisionDate} · {record.decision}</small></span></button><button aria-label={`${record.investmentName||"이름 없는 종목"} 기록 삭제`} type="button" onClick={()=>persist(records.filter(item=>item.id!==record.id))}><Trash2 size={15}/></button></div>)}</div><LegalDisclaimer/></aside></div>;
}

type Board = { financialAssets:number; cash:number; pension:number; realEstateEquity:number; debtBalance:number; debtRate:number; debtRemainingYears:number; monthlySalary:number; annualBonus:number; currentSideIncome:number; rentalIncome:number; fixedExpenses:number; currentSaving:number; currentInvesting:number; currentDebtPayment:number; salaryIncrease:number; housingSaving:number; foodSaving:number; transportSaving:number; subscriptionSaving:number; otherSaving:number; sideIncomeIncrease:number; monthlyInvestmentIncrease:number; extraDebtPayment:number; bonusInvested:number; assetSaleInvested:number; otherOneOff:number; expectedReturn:number; investRate:number; years:number };
const boardDefaults: Board = { financialAssets:50_000_000,cash:10_000_000,pension:10_000_000,realEstateEquity:0,debtBalance:100_000_000,debtRate:4.5,debtRemainingYears:20,monthlySalary:4_000_000,annualBonus:5_000_000,currentSideIncome:0,rentalIncome:0,fixedExpenses:2_500_000,currentSaving:700_000,currentInvesting:600_000,currentDebtPayment:500_000,salaryIncrease:300_000,housingSaving:300_000,foodSaving:100_000,transportSaving:50_000,subscriptionSaving:30_000,otherSaving:0,sideIncomeIncrease:200_000,monthlyInvestmentIncrease:200_000,extraDebtPayment:200_000,bonusInvested:5_000_000,assetSaleInvested:0,otherOneOff:0,expectedReturn:6,investRate:80,years:15 };
function remainingInterest(balance:number,annualRate:number,years:number,extraPayment:number){const months=Math.max(Math.floor(years*12),0);const rate=annualRate/100/12;const scheduled=monthlyLoanPayment(balance,annualRate,months);let remaining=Math.max(balance,0);let interestTotal=0;for(let month=0;month<months&&remaining>0.01;month+=1){const interest=remaining*rate;interestTotal+=interest;remaining+=interest;remaining-=Math.min(remaining,scheduled+Math.max(extraPayment,0))}return interestTotal}
export function GrowthLeverBoard() {
  const [input,setInput]=useState(boardDefaults); const [inputMode,setInputMode]=useState<InputMode>("quick"); const update=(key:keyof Board,value:number)=>setInput(c=>({...c,[key]:value})); const months=input.years*12; const netAssets=input.financialAssets+input.cash+input.pension+input.realEstateEquity-input.debtBalance; const regularIncome=input.monthlySalary+input.currentSideIncome+input.rentalIncome+input.annualBonus/12; const regularOutflow=input.fixedExpenses+input.currentSaving+input.currentInvesting+input.currentDebtPayment; const regularSurplus=regularIncome-regularOutflow; const savingsUnlocked=input.housingSaving+input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving;
  const levers=useMemo(()=>{const invest=input.investRate/100; const oneOff=input.bonusInvested+input.assetSaleInvested+input.otherOneOff; const baselineInterest=remainingInterest(input.debtBalance,input.debtRate,input.debtRemainingYears,0);const acceleratedInterest=remainingInterest(input.debtBalance,input.debtRate,input.debtRemainingYears,input.extraDebtPayment);return [
    {group:"소득",name:"월급 증가",action:`월급 증가분 ${formatMoney(input.salaryIncrease)} 중 ${input.investRate}% 투자`,monthly:input.salaryIncrease*invest,impact:recurringFutureValue(input.salaryIncrease*invest,input.expectedReturn,months)},
    {group:"절약",name:"주거비 절감",action:`이사·대환 등으로 월 ${formatMoney(input.housingSaving)} 확보`,monthly:input.housingSaving,impact:recurringFutureValue(input.housingSaving,input.expectedReturn,months)},
    {group:"절약",name:"생활비 절감",action:`식대·교통·구독·기타 월 ${formatMoney(input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving)} 확보`,monthly:input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving,impact:recurringFutureValue(input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving,input.expectedReturn,months)},
    {group:"부업",name:"부업·사업소득 증가",action:`월 ${formatMoney(input.sideIncomeIncrease)} 중 ${input.investRate}% 투자`,monthly:input.sideIncomeIncrease*invest,impact:recurringFutureValue(input.sideIncomeIncrease*invest,input.expectedReturn,months)},
    {group:"투자",name:"정기 투자금 증가",action:`월 투자금을 ${formatMoney(input.monthlyInvestmentIncrease)} 추가`,monthly:input.monthlyInvestmentIncrease,impact:recurringFutureValue(input.monthlyInvestmentIncrease,input.expectedReturn,months)},
    {group:"부채",name:"부채 추가 상환",action:`연 ${input.debtRate}%·잔여 ${input.debtRemainingYears}년 대출에 월 ${formatMoney(input.extraDebtPayment)} 추가`,monthly:input.extraDebtPayment,impact:Math.max(baselineInterest-acceleratedInterest,0)},
    {group:"일회성",name:"성과급·매각대금 투자",action:`일회성 유입 ${formatMoney(oneOff)} 투자`,monthly:0,impact:futureValue(oneOff,0,input.expectedReturn,months)},
  ]},[input,months]);
  return <div className="calculator-grid"><section className="input-panel"><div className="panel-heading"><div><span>QUARTERLY WEALTH SYSTEM</span><h2>현재 기반과 바꿀 수 있는 레버를 구분해 입력해 주세요</h2></div></div>
    <InputModeSwitch mode={inputMode} onChange={setInputMode} quickDescription="현재 자산·현금흐름과 이번에 바꿀 금액만 입력해 가장 영향이 큰 항목을 확인합니다." />
    <div className="field-section baseline-section"><h3>1. 현재 보유 자산과 부채</h3><div className="field-grid"><Field label="금융투자자산" value={input.financialAssets} onChange={v=>update("financialAssets",v)}/><Field label="현금성 자산" value={input.cash} onChange={v=>update("cash",v)}/><Field label="연금자산" value={input.pension} onChange={v=>update("pension",v)}/><Field label="부동산 순자산" value={input.realEstateEquity} onChange={v=>update("realEstateEquity",v)}/><Field label="전체 부채" value={input.debtBalance} onChange={v=>update("debtBalance",v)}/><Field label="부채 연이율" value={input.debtRate} onChange={v=>update("debtRate",v)} unit="%" max={50}/><Field label="부채 잔여기간" value={input.debtRemainingYears} onChange={v=>update("debtRemainingYears",v)} unit="년" min={1} max={50}/></div></div>
    <div className="field-section baseline-section"><h3>2. 현재 정기 현금흐름</h3><div className="field-grid"><Field label="세후 월급" value={input.monthlySalary} onChange={v=>update("monthlySalary",v)}/><Field label="연간 성과급·상여" value={input.annualBonus} onChange={v=>update("annualBonus",v)}/>{inputMode === "detailed" && <><Field label="현재 월 부업소득" value={input.currentSideIncome} onChange={v=>update("currentSideIncome",v)}/><Field label="월 임대소득" value={input.rentalIncome} onChange={v=>update("rentalIncome",v)}/></>}<Field label="월 고정생활비" value={input.fixedExpenses} onChange={v=>update("fixedExpenses",v)}/><Field label="월 저축" value={input.currentSaving} onChange={v=>update("currentSaving",v)}/><Field label="월 투자" value={input.currentInvesting} onChange={v=>update("currentInvesting",v)}/><Field label="월 부채상환" value={input.currentDebtPayment} onChange={v=>update("currentDebtPayment",v)}/></div></div>
    <div className="field-section lever-section"><h3>3. 이번 분기에 바꿀 수 있는 월 레버</h3><div className="field-grid"><Field label="월급 증가분" value={input.salaryIncrease} onChange={v=>update("salaryIncrease",v)}/><Field label="월 주거비 절감" value={input.housingSaving} onChange={v=>update("housingSaving",v)}/>{inputMode === "quick" ? <Field label="월 생활비 절감" value={input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving} onChange={v=>setInput(c=>({...c,foodSaving:v,transportSaving:0,subscriptionSaving:0,otherSaving:0}))}/> : <><Field label="월 식대 절감" value={input.foodSaving} onChange={v=>update("foodSaving",v)}/><Field label="월 교통비 절감" value={input.transportSaving} onChange={v=>update("transportSaving",v)}/><Field label="월 구독비 절감" value={input.subscriptionSaving} onChange={v=>update("subscriptionSaving",v)}/><Field label="월 기타비용 절감" value={input.otherSaving} onChange={v=>update("otherSaving",v)}/></>}<Field label="월 부업소득 증가" value={input.sideIncomeIncrease} onChange={v=>update("sideIncomeIncrease",v)}/><Field label="월 투자금 추가" value={input.monthlyInvestmentIncrease} onChange={v=>update("monthlyInvestmentIncrease",v)}/><Field label="월 부채 추가상환" value={input.extraDebtPayment} onChange={v=>update("extraDebtPayment",v)}/></div></div>
    <div className="field-section oneoff-section"><h3>4. 일회성으로 들어온 돈의 배분</h3><div className="field-grid"><Field label="투자할 성과급" value={input.bonusInvested} onChange={v=>update("bonusInvested",v)}/>{inputMode === "detailed" && <><Field label="투자할 자산 매각대금" value={input.assetSaleInvested} onChange={v=>update("assetSaleInvested",v)}/><Field label="환급금·기타 일회성 투자" value={input.otherOneOff} onChange={v=>update("otherOneOff",v)}/></>}</div></div>
    <div className="field-section"><h3>5. 공통 가정</h3><div className="field-grid"><Field label="기대수익률" value={input.expectedReturn} onChange={v=>update("expectedReturn",v)} unit="%" max={30}/>{inputMode === "detailed" && <Field label="증가 소득 투자비율" value={input.investRate} onChange={v=>update("investRate",v)} unit="%" max={100}/>}<Field label="영향 비교기간" value={input.years} onChange={v=>update("years",v)} unit="년" min={1} max={30}/></div></div><QuickAssumptionNote mode={inputMode}>현재 부업·임대소득은 예시값 0원, 증가 소득의 80%를 투자한다고 가정합니다. 매각대금·기타 일회성 자금은 0원입니다.</QuickAssumptionNote></section>
    <section className="result-panel"><QuickEstimateNotice mode={inputMode} /><div className="verdict-line"><span>입력 가정별 영향 비교</span><strong className="verdict">{input.years}년 시나리오</strong><p>금액이 큰 항목을 자동 추천하거나 우선순위로 판정하지 않습니다. 실행난이도와 위험은 사용자가 따로 판단해야 합니다.</p></div><div className="kpi-grid"><div className="kpi"><span>현재 순자산</span><strong>{formatMoney(netAssets)}</strong></div><div className="kpi"><span>현재 월 정기수입</span><strong>{formatMoney(regularIncome)}</strong></div><div className="kpi"><span>정기 현금흐름 잔액</span><strong>{formatMoney(regularSurplus)}</strong></div></div><div className="flow-summary"><div><span>절약으로 확보 가능한 월 투자금</span><strong>{formatMoney(savingsUnlocked)}</strong></div><div><span>현재 월 저축·투자</span><strong>{formatMoney(input.currentSaving+input.currentInvesting)}</strong></div><div><span>일회성 투자 예정액</span><strong>{formatMoney(input.bonusInvested+input.assetSaleInvested+input.otherOneOff)}</strong></div></div><div className="lever-list">{levers.map(lever=><div key={lever.name}><b>•</b><span><em>{lever.group}</em>{lever.name}<small>{lever.action}</small></span><strong>{formatMoney(lever.impact)}</strong></div>)}</div><div className="warning-strip"><Target size={17}/><span>투자 레버는 입력 수익률의 미래가치, 부채 레버는 입력한 대출조건에서 추가상환으로 줄어드는 총이자입니다. 서로 성격이 다른 추정치이며 세금·위험·실행 가능성은 포함하지 않습니다.</span></div><LegalDisclaimer/></section></div>;
}
