"use client";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Check, Download, FileText, Save, Target, Trash2 } from "lucide-react";
import { formatMoney, futureValue, recurringFutureValue } from "../lib/finance";
import { LegalDisclaimer } from "./SiteChrome";

function Field({ label, value, onChange, unit = "원", min = 0, max = 10_000_000_000 }: { label: string; value: number; onChange: (v: number) => void; unit?: string; min?: number; max?: number }) { return <label className="field"><span className="field-label">{label}</span><span className="input-wrap"><input value={unit === "원" ? Math.round(value).toLocaleString("ko-KR") : value} onChange={(e) => { const raw = e.target.value.replace(min < 0 ? /[^0-9.-]/g : /[^0-9.]/g, ""); onChange(Math.min(Math.max(Number(raw) || 0, min), max)); }} /><span>{unit}</span></span></label>; }
function TextField({ label, value, onChange, hint }: { label: string; value: string; onChange: (v: string) => void; hint?: string }) { return <label className="note-field"><span>{label}</span><textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder={hint} rows={3} /></label>; }

type Metric = number | null;
type Journal = {
  id: string; investmentName: string; ticker: string; market: string; industry: string; decision: string; decisionDate: string; reviewDate: string; moatType: string;
  currentPrice: Metric; entryPrice: Metric; shares: Metric; amount: Metric; marketCap: Metric; portfolioWeight: Metric; holdingMonths: Metric;
  per: Metric; industryPer: Metric; forwardPer: Metric; pbr: Metric; evEbitda: Metric; fcfYield: Metric; dividendYield: Metric;
  revenueOld: Metric; revenueMid: Metric; revenueRecent: Metric; operatingProfitOld: Metric; operatingProfitMid: Metric; operatingProfitRecent: Metric;
  netIncome: Metric; operatingCashFlow: Metric; capex: Metric; roe: Metric; roic: Metric; debtRatio: Metric; netDebtEbitda: Metric; interestCoverage: Metric;
  expectedReturn: Metric; worstLoss: Metric; probability: Metric; estimatedValue: Metric;
  thesis: string; invalidation: string; keyRisk: string; sellCondition: string; sources: string;
  actualReturn: Metric; actualResult: string; rulesKept: Metric; lesson: string;
};
const today = () => new Date().toISOString().slice(0, 10);
const journalDefaults: Journal = {
  id: "", investmentName: "", ticker: "", market: "한국", industry: "", decision: "매수 검토", decisionDate: today(), reviewDate: "", moatType: "아직 판단하지 않음",
  currentPrice: null, entryPrice: null, shares: null, amount: null, marketCap: null, portfolioWeight: null, holdingMonths: 36,
  per: null, industryPer: null, forwardPer: null, pbr: null, evEbitda: null, fcfYield: null, dividendYield: null,
  revenueOld: null, revenueMid: null, revenueRecent: null, operatingProfitOld: null, operatingProfitMid: null, operatingProfitRecent: null,
  netIncome: null, operatingCashFlow: null, capex: null, roe: null, roic: null, debtRatio: null, netDebtEbitda: null, interestCoverage: null,
  expectedReturn: 10, worstLoss: 30, probability: 60, estimatedValue: null,
  thesis: "", invalidation: "", keyRisk: "", sellCondition: "", sources: "",
  actualReturn: null, actualResult: "", rulesKept: null, lesson: "",
};
function MetricField({label,value,onChange,unit="배",min=-1_000_000_000,max=1_000_000_000_000_000,hint}:{label:string;value:Metric;onChange:(v:Metric)=>void;unit?:string;min?:number;max?:number;hint?:string}){return <label className="field metric-field"><span className="field-label">{label}</span><span className="input-wrap"><input inputMode="decimal" value={value ?? ""} placeholder="미입력" onChange={(event)=>{const raw=event.target.value.replace(/[^0-9.-]/g,"");if(raw===""||raw==="-"||raw==="."){onChange(null);return}onChange(Math.min(Math.max(Number(raw),min),max))}}/><span>{unit}</span></span>{hint&&<small>{hint}</small>}</label>}
function ShortText({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="field"><span className="field-label">{label}</span><span className="input-wrap text-input"><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></span></label>}
function JournalSelect({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="field"><span className="field-label">{label}</span><span className="select-wrap"><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></span></label>}
const present=(value:Metric):value is number=>value!==null&&Number.isFinite(value);
const ratio=(numerator:Metric,denominator:Metric)=>present(numerator)&&present(denominator)&&denominator!==0?numerator/denominator*100:null;
const cagr=(start:Metric,end:Metric,years:number)=>present(start)&&present(end)&&start>0&&end>0?(Math.pow(end/start,1/years)-1)*100:null;
const metricText=(value:Metric,unit="%",digits=1)=>present(value)?`${value.toFixed(digits)}${unit}`:"—";
const masters = [
  { name: "버핏·멍거", principle: "사업의 경제성과 지속성", note: "한 문장 투자논지와 경쟁우위 유형만 남기고, 실제 수익성은 영업이익률·ROIC·현금흐름으로 확인합니다." },
  { name: "벤저민 그레이엄", principle: "가격과 가치의 차이", note: "적정가 대비 안전마진과 업종 PER 대비 할인·프리미엄을 숫자로 기록합니다." },
  { name: "피터 린치", principle: "스토리와 숫자의 일치", note: "3개년 매출·영업이익·마진 추세가 투자논지를 뒷받침하는지 확인합니다." },
  { name: "달리오·하워드 막스", principle: "반증과 손실 통제", note: "논지가 깨지는 조건, 최대손실, 확률과 포트폴리오 비중만 필수 정성·위험 항목으로 남깁니다." },
];
export function DecisionJournal() {
  const [input,setInput]=useState<Journal>(journalDefaults); const [records,setRecords]=useState<Journal[]>([]); const [saved,setSaved]=useState(false);
  useEffect(()=>{try{const value=localStorage.getItem("wdl-investment-journal");if(value){const parsed=JSON.parse(value) as Partial<Journal>[];setRecords(parsed.map(record=>({...journalDefaults,...record})))}}catch{}},[]);
  const update=<K extends keyof Journal>(key:K,value:Journal[K])=>setInput(current=>({...current,[key]:value}));
  const margins=[ratio(input.operatingProfitOld,input.revenueOld),ratio(input.operatingProfitMid,input.revenueMid),ratio(input.operatingProfitRecent,input.revenueRecent)];
  const revenueCagr=cagr(input.revenueOld,input.revenueRecent,2); const operatingProfitCagr=cagr(input.operatingProfitOld,input.operatingProfitRecent,2);
  const marginTrend=present(margins[0])&&present(margins[2])?margins[2]-margins[0]:null;
  const perGap=present(input.per)&&present(input.industryPer)&&input.industryPer!==0?(input.per/input.industryPer-1)*100:null;
  const cashConversion=ratio(input.operatingCashFlow,input.netIncome); const freeCashFlow=present(input.operatingCashFlow)&&present(input.capex)?input.operatingCashFlow-input.capex:null;
  const referencePrice=present(input.entryPrice)?input.entryPrice:input.currentPrice; const safetyMargin=present(input.estimatedValue)&&present(referencePrice)&&input.estimatedValue!==0?(input.estimatedValue-referencePrice)/input.estimatedValue*100:null;
  const checks=[
    {label:"업종 PER 이하",value:present(input.per)&&present(input.industryPer)&&input.per>0&&input.industryPer>0?input.per<=input.industryPer:null,detail:present(perGap)?`업종 대비 ${Math.abs(perGap).toFixed(1)}% ${perGap<=0?"할인":"프리미엄"}`:"흑자기업의 동일 기준 PER 입력 필요"},
    {label:"선행 PER 개선",value:present(input.per)&&present(input.forwardPer)&&input.per>0&&input.forwardPer>0?input.forwardPer<=input.per:null,detail:"선행 PER이 현재 PER 이하인지 확인"},
    {label:"3개년 매출 성장",value:present(revenueCagr)?revenueCagr>=0:null,detail:`CAGR ${metricText(revenueCagr)}`},
    {label:"영업이익률 유지·개선",value:present(marginTrend)?marginTrend>=0:null,detail:`3개년 변화 ${metricText(marginTrend,"%p")}`},
    {label:"ROIC가 요구수익률 이상",value:present(input.roic)&&present(input.expectedReturn)?input.roic>=input.expectedReturn:null,detail:`ROIC ${metricText(input.roic)} · 요구 ${metricText(input.expectedReturn)}`},
    {label:"현금전환율 80% 이상",value:present(cashConversion)?cashConversion>=80:null,detail:`영업현금흐름 ÷ 순이익 ${metricText(cashConversion)}`},
    {label:"잉여현금흐름 흑자",value:present(freeCashFlow)?freeCashFlow>=0:null,detail:`영업현금흐름 − CAPEX ${present(freeCashFlow)?freeCashFlow.toLocaleString("ko-KR")+"억원":"—"}`},
    {label:"부채비율 200% 이하",value:present(input.debtRatio)?input.debtRatio<=200:null,detail:`현재 ${metricText(input.debtRatio)}`},
    {label:"순차입금/EBITDA 3배 이하",value:present(input.netDebtEbitda)?input.netDebtEbitda<=3:null,detail:`현재 ${metricText(input.netDebtEbitda,"배")}`},
    {label:"이자보상배율 3배 이상",value:present(input.interestCoverage)?input.interestCoverage>=3:null,detail:`현재 ${metricText(input.interestCoverage,"배")}`},
  ];
  const availableChecks=checks.filter(check=>check.value!==null); const passedChecks=availableChecks.filter(check=>check.value).length; const failedChecks=availableChecks.length-passedChecks;
  const completenessValues=[input.investmentName,input.ticker,input.industry,input.currentPrice,input.per,input.industryPer,input.revenueOld,input.revenueMid,input.revenueRecent,input.operatingProfitOld,input.operatingProfitMid,input.operatingProfitRecent,input.roic,input.debtRatio,input.operatingCashFlow,input.netIncome,input.thesis,input.invalidation,input.sellCondition,input.sources];
  const completeness=Math.round(completenessValues.filter(value=>typeof value==="string"?value.trim().length>0:present(value)).length/completenessValues.length*100);
  const status=completeness<60?"기초 데이터 입력 중":failedChecks>=4?"위험 신호 우선 점검":"정량 검토 완료";
  const persist=(next:Journal[])=>{setRecords(next);localStorage.setItem("wdl-investment-journal",JSON.stringify(next))};
  const save=()=>{const record={...input,id:input.id||`${Date.now()}`};const next=input.id?records.map(item=>item.id===input.id?record:item):[record,...records];persist(next);setInput(record);setSaved(true);setTimeout(()=>setSaved(false),1500)};
  const download=()=>{const payload={exportedAt:new Date().toISOString(),guide:"기업가치·3개년 실적·현금흐름 중심의 주식 투자 기록",records:records.length?records:[{...input,derived:{margins,revenueCagr,operatingProfitCagr,perGap,cashConversion,freeCashFlow,safetyMargin,passedChecks,availableChecks:availableChecks.length}}]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=`stock-investment-journal-${today()}.json`;anchor.click();URL.revokeObjectURL(anchor.href)};
  const openBacktest=()=>{sessionStorage.setItem("wdl-backtest-screening",JSON.stringify({requiredReturn:input.expectedReturn??10,minimumPass:Math.max(Math.min(passedChecks||7,10),1),minimumValid:Math.max(Math.min(availableChecks.length||7,10),1)}));window.location.assign("/invest/quant-backtest")};
  return <div className="journal-layout"><section className="input-panel"><div className="panel-heading"><div><span>QUANTITATIVE INVESTMENT JOURNAL</span><h2>주식의 매수 이유는 기록해야 합니다.</h2></div></div>
    <div className="journal-notice"><strong>입력 원칙</strong><span>같은 회계기준·같은 기간의 연결재무제표를 사용하세요. 금융회사·리츠·유틸리티는 부채와 현금흐름 기준이 달라 아래 공통 판정을 그대로 적용하기 어렵습니다.</span></div>
    <div className="field-section"><h3>1. 종목과 매수 계획</h3><div className="field-grid"><ShortText label="기업명" value={input.investmentName} onChange={v=>update("investmentName",v)} placeholder="예: 삼성전자"/><ShortText label="티커·종목코드" value={input.ticker} onChange={v=>update("ticker",v)} placeholder="예: 005930"/><ShortText label="시장" value={input.market} onChange={v=>update("market",v)} placeholder="한국·미국"/><ShortText label="산업·업종" value={input.industry} onChange={v=>update("industry",v)} placeholder="동일 비교군 기준"/><JournalSelect label="현재 결정" value={input.decision} onChange={v=>update("decision",v)}><option>매수 검토</option><option>보유 점검</option><option>추가매수 검토</option><option>매도 검토</option></JournalSelect><JournalSelect label="경쟁우위 유형" value={input.moatType} onChange={v=>update("moatType",v)}><option>아직 판단하지 않음</option><option>브랜드·가격결정력</option><option>네트워크 효과</option><option>전환비용</option><option>원가우위</option><option>규모의 경제</option><option>규제·특허</option><option>뚜렷한 우위 없음</option></JournalSelect><ShortText label="결정일" type="date" value={input.decisionDate} onChange={v=>update("decisionDate",v)}/><ShortText label="다음 점검일" type="date" value={input.reviewDate} onChange={v=>update("reviewDate",v)}/></div><div className="field-grid"><MetricField label="현재 주가" value={input.currentPrice} onChange={v=>update("currentPrice",v)} unit="원"/><MetricField label="검토 매수가" value={input.entryPrice} onChange={v=>update("entryPrice",v)} unit="원"/><MetricField label="매수 수량" value={input.shares} onChange={v=>update("shares",v)} unit="주"/><MetricField label="투자 예정액" value={input.amount} onChange={v=>update("amount",v)} unit="원"/><MetricField label="시가총액" value={input.marketCap} onChange={v=>update("marketCap",v)} unit="억원"/><MetricField label="투자 후 비중" value={input.portfolioWeight} onChange={v=>update("portfolioWeight",v)} unit="%" min={0} max={100}/><MetricField label="예상 보유기간" value={input.holdingMonths} onChange={v=>update("holdingMonths",v)} unit="개월" min={1} max={600}/></div></div>
    <div className="field-section valuation-section"><h3>2. 상대가치와 시장 기대</h3><p className="section-help">기업과 업종은 같은 기준의 후행 PER을 사용하고, 적자기업은 PER 비교 대신 매출·현금흐름과 손익분기 시점을 별도로 확인하세요.</p><div className="field-grid"><MetricField label="기업 PER" value={input.per} onChange={v=>update("per",v)}/><MetricField label="동일 산업 PER" value={input.industryPer} onChange={v=>update("industryPer",v)} hint="국가·업종·시점이 같은 비교군"/><MetricField label="선행 PER" value={input.forwardPer} onChange={v=>update("forwardPer",v)}/><MetricField label="PBR" value={input.pbr} onChange={v=>update("pbr",v)}/><MetricField label="EV/EBITDA" value={input.evEbitda} onChange={v=>update("evEbitda",v)}/><MetricField label="FCF 수익률" value={input.fcfYield} onChange={v=>update("fcfYield",v)} unit="%"/><MetricField label="배당수익률" value={input.dividendYield} onChange={v=>update("dividendYield",v)} unit="%"/><MetricField label="적정가·내재가치" value={input.estimatedValue} onChange={v=>update("estimatedValue",v)} unit="원"/></div></div>
    <div className="field-section"><h3>3. 3개년 매출·영업이익</h3><p className="section-help">전전년부터 최근연도까지 같은 단위로 입력하면 영업이익률과 연평균성장률을 자동 계산합니다.</p><div className="financial-years"><article><span>전전년 · Y-2</span><MetricField label="매출" value={input.revenueOld} onChange={v=>update("revenueOld",v)} unit="억원"/><MetricField label="영업이익" value={input.operatingProfitOld} onChange={v=>update("operatingProfitOld",v)} unit="억원"/><strong>영업이익률 {metricText(margins[0])}</strong></article><article><span>전년 · Y-1</span><MetricField label="매출" value={input.revenueMid} onChange={v=>update("revenueMid",v)} unit="억원"/><MetricField label="영업이익" value={input.operatingProfitMid} onChange={v=>update("operatingProfitMid",v)} unit="억원"/><strong>영업이익률 {metricText(margins[1])}</strong></article><article><span>최근연도 · Y0</span><MetricField label="매출" value={input.revenueRecent} onChange={v=>update("revenueRecent",v)} unit="억원"/><MetricField label="영업이익" value={input.operatingProfitRecent} onChange={v=>update("operatingProfitRecent",v)} unit="억원"/><strong>영업이익률 {metricText(margins[2])}</strong></article></div><div className="derived-strip"><div><span>매출 CAGR</span><strong>{metricText(revenueCagr)}</strong></div><div><span>영업이익 CAGR</span><strong>{metricText(operatingProfitCagr)}</strong></div><div><span>영업이익률 변화</span><strong>{metricText(marginTrend,"%p")}</strong></div></div></div>
    <div className="field-section"><h3>4. 수익성·현금흐름·재무안전성</h3><div className="field-grid"><MetricField label="ROE" value={input.roe} onChange={v=>update("roe",v)} unit="%"/><MetricField label="ROIC" value={input.roic} onChange={v=>update("roic",v)} unit="%"/><MetricField label="최근 순이익" value={input.netIncome} onChange={v=>update("netIncome",v)} unit="억원"/><MetricField label="최근 영업현금흐름" value={input.operatingCashFlow} onChange={v=>update("operatingCashFlow",v)} unit="억원"/><MetricField label="최근 CAPEX" value={input.capex} onChange={v=>update("capex",v)} unit="억원"/><MetricField label="부채비율" value={input.debtRatio} onChange={v=>update("debtRatio",v)} unit="%"/><MetricField label="순차입금/EBITDA" value={input.netDebtEbitda} onChange={v=>update("netDebtEbitda",v)}/><MetricField label="이자보상배율" value={input.interestCoverage} onChange={v=>update("interestCoverage",v)}/></div><div className="derived-strip"><div><span>현금전환율</span><strong>{metricText(cashConversion)}</strong></div><div><span>추정 FCF</span><strong>{present(freeCashFlow)?freeCashFlow.toLocaleString("ko-KR")+"억원":"—"}</strong></div><div><span>안전마진</span><strong>{metricText(safetyMargin)}</strong></div></div></div>
    <div className="field-section"><h3>5. 기대수익과 손실 계획</h3><div className="field-grid"><MetricField label="요구·기대수익률" value={input.expectedReturn} onChange={v=>update("expectedReturn",v)} unit="%" min={-100} max={500}/><MetricField label="예상 최대손실" value={input.worstLoss} onChange={v=>update("worstLoss",v)} unit="%" min={0} max={100}/><MetricField label="논지 실현 확률" value={input.probability} onChange={v=>update("probability",v)} unit="%" min={0} max={100}/></div></div>
    <div className="field-section qualitative-core"><h3>6. 숫자로 대체할 수 없는 필수 기록</h3><p className="section-help">설명문은 다섯 칸만 남겼습니다. 수치가 왜 지속될지와 어떤 조건에서 판단을 바꿀지만 짧게 기록하세요.</p><div className="note-grid"><TextField label="한 문장 투자논지" value={input.thesis} onChange={v=>update("thesis",v)} hint="무엇이 언제까지 기업가치를 높인다고 보는지 한 문장으로 적어 주세요."/><TextField label="논지가 깨지는 조건" value={input.invalidation} onChange={v=>update("invalidation",v)} hint="수치와 기한을 포함하면 좋습니다."/><TextField label="가장 큰 비정량 위험" value={input.keyRisk} onChange={v=>update("keyRisk",v)} hint="규제, 지배구조, 기술 대체 등 숫자에 아직 드러나지 않은 위험"/><TextField label="매도·축소 조건" value={input.sellCondition} onChange={v=>update("sellCondition",v)} hint="가격이 아니라 논지·밸류에이션·비중 기준으로 적어 주세요."/><TextField label="재무제표·산업 비교 출처" value={input.sources} onChange={v=>update("sources",v)} hint="사업보고서 기준일, 데이터 URL, 업종 비교군을 기록해 주세요."/></div></div>
    <div className="field-section"><h3>7. 투자 후 복기</h3><div className="field-grid"><MetricField label="실제 수익률" value={input.actualReturn} onChange={v=>update("actualReturn",v)} unit="%" min={-100} max={1000}/><MetricField label="사전 규칙 준수" value={input.rulesKept} onChange={v=>update("rulesKept",v)} unit="/ 5" min={1} max={5}/></div><div className="note-grid"><TextField label="실제 결과와 예상의 차이" value={input.actualResult} onChange={v=>update("actualResult",v)}/><TextField label="다음 투자에 반영할 한 가지" value={input.lesson} onChange={v=>update("lesson",v)}/></div></div>
    <div className="result-actions journal-actions"><button className="primary-button" type="button" onClick={save}>{saved?<Check size={17}/>:<Save size={17}/>} {saved?"저장되었습니다":"투자 기록 저장"}</button><button className="secondary-button" type="button" onClick={download}><Download size={17}/> 전체 기록 JSON</button><button className="secondary-button backtest-link-button" type="button" onClick={openBacktest}><BarChart3 size={17}/> 이 기준으로 백테스트하기</button></div></section>
    <aside className="result-panel journal-side"><div className="verdict-line"><span>정량 점검 상태</span><strong className="verdict">{status}</strong><p>매수 추천 점수가 아니라 입력 완성도와 공개 기준의 주의 항목을 보여줍니다.</p></div><div className="kpi-grid"><div className="kpi"><span>필수 데이터 완성도</span><strong>{completeness}%</strong></div><div className="kpi"><span>정량 기준 통과</span><strong>{passedChecks} / {availableChecks.length}</strong></div><div className="kpi"><span>주의 항목</span><strong>{failedChecks}개</strong></div></div><div className="journal-metrics"><div><span>업종 대비 PER</span><strong>{present(perGap)?`${Math.abs(perGap).toFixed(1)}% ${perGap<=0?"할인":"프리미엄"}`:"—"}</strong></div><div><span>3개년 매출 CAGR</span><strong>{metricText(revenueCagr)}</strong></div><div><span>영업이익률 변화</span><strong>{metricText(marginTrend,"%p")}</strong></div><div><span>현금전환율</span><strong>{metricText(cashConversion)}</strong></div></div><div className="quant-checks"><h3>공개된 정량 점검 규칙</h3>{checks.map(check=><div className={check.value===null?"is-empty":check.value?"is-pass":"is-warn"} key={check.label}><b>{check.value===null?"—":check.value?"통과":"주의"}</b><span>{check.label}<small>{check.detail}</small></span></div>)}</div><div className="master-checklist"><h3>남겨 둔 거장 관점</h3>{masters.map(master=><details key={master.name}><summary>{master.name} · {master.principle}</summary><p>{master.note}</p></details>)}</div><div className="saved-records"><h3>이 브라우저에 저장된 기록</h3>{records.length===0?<p>아직 저장된 기록이 없습니다.</p>:records.map(record=><div key={record.id}><button type="button" onClick={()=>setInput({...journalDefaults,...record})}><FileText size={15}/><span>{record.investmentName||"이름 없는 종목"}<small>{record.ticker||"티커 미입력"} · {record.decisionDate} · {record.decision}</small></span></button><button aria-label="기록 삭제" type="button" onClick={()=>persist(records.filter(item=>item.id!==record.id))}><Trash2 size={15}/></button></div>)}</div><LegalDisclaimer/></aside></div>;
}

type Board = { financialAssets:number; cash:number; pension:number; realEstateEquity:number; debtBalance:number; monthlySalary:number; annualBonus:number; currentSideIncome:number; rentalIncome:number; fixedExpenses:number; currentSaving:number; currentInvesting:number; currentDebtPayment:number; salaryIncrease:number; housingSaving:number; foodSaving:number; transportSaving:number; subscriptionSaving:number; otherSaving:number; sideIncomeIncrease:number; monthlyInvestmentIncrease:number; extraDebtPayment:number; bonusInvested:number; assetSaleInvested:number; otherOneOff:number; expectedReturn:number; investRate:number; years:number };
const boardDefaults: Board = { financialAssets:50_000_000,cash:10_000_000,pension:10_000_000,realEstateEquity:0,debtBalance:100_000_000,monthlySalary:4_000_000,annualBonus:5_000_000,currentSideIncome:0,rentalIncome:0,fixedExpenses:2_500_000,currentSaving:700_000,currentInvesting:600_000,currentDebtPayment:500_000,salaryIncrease:300_000,housingSaving:300_000,foodSaving:100_000,transportSaving:50_000,subscriptionSaving:30_000,otherSaving:0,sideIncomeIncrease:200_000,monthlyInvestmentIncrease:200_000,extraDebtPayment:200_000,bonusInvested:5_000_000,assetSaleInvested:0,otherOneOff:0,expectedReturn:6,investRate:80,years:15 };
export function GrowthLeverBoard() {
  const [input,setInput]=useState(boardDefaults); const update=(key:keyof Board,value:number)=>setInput(c=>({...c,[key]:value})); const months=input.years*12; const netAssets=input.financialAssets+input.cash+input.pension+input.realEstateEquity-input.debtBalance; const regularIncome=input.monthlySalary+input.currentSideIncome+input.rentalIncome+input.annualBonus/12; const regularOutflow=input.fixedExpenses+input.currentSaving+input.currentInvesting+input.currentDebtPayment; const regularSurplus=regularIncome-regularOutflow; const savingsUnlocked=input.housingSaving+input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving;
  const levers=useMemo(()=>{const invest=input.investRate/100; const oneOff=input.bonusInvested+input.assetSaleInvested+input.otherOneOff; return [
    {group:"소득",name:"월급 증가",action:`월급 증가분 ${formatMoney(input.salaryIncrease)} 중 ${input.investRate}% 투자`,monthly:input.salaryIncrease*invest,impact:recurringFutureValue(input.salaryIncrease*invest,input.expectedReturn,months)},
    {group:"절약",name:"주거비 절감",action:`이사·대환 등으로 월 ${formatMoney(input.housingSaving)} 확보`,monthly:input.housingSaving,impact:recurringFutureValue(input.housingSaving,input.expectedReturn,months)},
    {group:"절약",name:"생활비 절감",action:`식대·교통·구독·기타 월 ${formatMoney(input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving)} 확보`,monthly:input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving,impact:recurringFutureValue(input.foodSaving+input.transportSaving+input.subscriptionSaving+input.otherSaving,input.expectedReturn,months)},
    {group:"부업",name:"부업·사업소득 증가",action:`월 ${formatMoney(input.sideIncomeIncrease)} 중 ${input.investRate}% 투자`,monthly:input.sideIncomeIncrease*invest,impact:recurringFutureValue(input.sideIncomeIncrease*invest,input.expectedReturn,months)},
    {group:"투자",name:"정기 투자금 증가",action:`월 투자금을 ${formatMoney(input.monthlyInvestmentIncrease)} 추가`,monthly:input.monthlyInvestmentIncrease,impact:recurringFutureValue(input.monthlyInvestmentIncrease,input.expectedReturn,months)},
    {group:"부채",name:"부채 추가 상환",action:`월 ${formatMoney(input.extraDebtPayment)} 추가 상환`,monthly:input.extraDebtPayment,impact:Math.min(input.extraDebtPayment*months,input.debtBalance)*.045*input.years/2},
    {group:"일회성",name:"성과급·매각대금 투자",action:`일회성 유입 ${formatMoney(oneOff)} 투자`,monthly:0,impact:futureValue(oneOff,0,input.expectedReturn,months)},
  ].sort((a,b)=>b.impact-a.impact)},[input,months]);
  return <div className="calculator-grid"><section className="input-panel"><div className="panel-heading"><div><span>QUARTERLY WEALTH SYSTEM</span><h2>현재 기반과 바꿀 수 있는 레버를 구분해 입력해 주세요</h2></div></div>
    <div className="field-section baseline-section"><h3>1. 현재 보유 자산과 부채</h3><div className="field-grid"><Field label="금융투자자산" value={input.financialAssets} onChange={v=>update("financialAssets",v)}/><Field label="현금성 자산" value={input.cash} onChange={v=>update("cash",v)}/><Field label="연금자산" value={input.pension} onChange={v=>update("pension",v)}/><Field label="부동산 순자산" value={input.realEstateEquity} onChange={v=>update("realEstateEquity",v)}/><Field label="전체 부채" value={input.debtBalance} onChange={v=>update("debtBalance",v)}/></div></div>
    <div className="field-section baseline-section"><h3>2. 현재 정기 현금흐름</h3><div className="field-grid"><Field label="세후 월급" value={input.monthlySalary} onChange={v=>update("monthlySalary",v)}/><Field label="연간 성과급·상여" value={input.annualBonus} onChange={v=>update("annualBonus",v)}/><Field label="현재 월 부업소득" value={input.currentSideIncome} onChange={v=>update("currentSideIncome",v)}/><Field label="월 임대소득" value={input.rentalIncome} onChange={v=>update("rentalIncome",v)}/><Field label="월 고정생활비" value={input.fixedExpenses} onChange={v=>update("fixedExpenses",v)}/><Field label="월 저축" value={input.currentSaving} onChange={v=>update("currentSaving",v)}/><Field label="월 투자" value={input.currentInvesting} onChange={v=>update("currentInvesting",v)}/><Field label="월 부채상환" value={input.currentDebtPayment} onChange={v=>update("currentDebtPayment",v)}/></div></div>
    <div className="field-section lever-section"><h3>3. 이번 분기에 바꿀 수 있는 월 레버</h3><div className="field-grid"><Field label="월급 증가분" value={input.salaryIncrease} onChange={v=>update("salaryIncrease",v)}/><Field label="월 주거비 절감" value={input.housingSaving} onChange={v=>update("housingSaving",v)}/><Field label="월 식대 절감" value={input.foodSaving} onChange={v=>update("foodSaving",v)}/><Field label="월 교통비 절감" value={input.transportSaving} onChange={v=>update("transportSaving",v)}/><Field label="월 구독비 절감" value={input.subscriptionSaving} onChange={v=>update("subscriptionSaving",v)}/><Field label="월 기타비용 절감" value={input.otherSaving} onChange={v=>update("otherSaving",v)}/><Field label="월 부업소득 증가" value={input.sideIncomeIncrease} onChange={v=>update("sideIncomeIncrease",v)}/><Field label="월 투자금 추가" value={input.monthlyInvestmentIncrease} onChange={v=>update("monthlyInvestmentIncrease",v)}/><Field label="월 부채 추가상환" value={input.extraDebtPayment} onChange={v=>update("extraDebtPayment",v)}/></div></div>
    <div className="field-section oneoff-section"><h3>4. 일회성으로 들어온 돈의 배분</h3><div className="field-grid"><Field label="투자할 성과급" value={input.bonusInvested} onChange={v=>update("bonusInvested",v)}/><Field label="투자할 자산 매각대금" value={input.assetSaleInvested} onChange={v=>update("assetSaleInvested",v)}/><Field label="환급금·기타 일회성 투자" value={input.otherOneOff} onChange={v=>update("otherOneOff",v)}/></div></div>
    <div className="field-section"><h3>5. 공통 가정</h3><div className="field-grid"><Field label="기대수익률" value={input.expectedReturn} onChange={v=>update("expectedReturn",v)} unit="%" max={30}/><Field label="증가 소득 투자비율" value={input.investRate} onChange={v=>update("investRate",v)} unit="%" max={100}/><Field label="영향 비교기간" value={input.years} onChange={v=>update("years",v)} unit="년" min={1} max={30}/></div></div></section>
    <section className="result-panel"><div className="verdict-line"><span>이번 분기 1순위 성장 레버</span><strong className="verdict">{levers[0].name}</strong><p>{levers[0].action}</p></div><div className="kpi-grid"><div className="kpi"><span>현재 순자산</span><strong>{formatMoney(netAssets)}</strong></div><div className="kpi"><span>현재 월 정기수입</span><strong>{formatMoney(regularIncome)}</strong></div><div className="kpi"><span>정기 현금흐름 잔액</span><strong>{formatMoney(regularSurplus)}</strong></div></div><div className="flow-summary"><div><span>절약으로 확보 가능한 월 투자금</span><strong>{formatMoney(savingsUnlocked)}</strong></div><div><span>현재 월 저축·투자</span><strong>{formatMoney(input.currentSaving+input.currentInvesting)}</strong></div><div><span>일회성 투자 예정액</span><strong>{formatMoney(input.bonusInvested+input.assetSaleInvested+input.otherOneOff)}</strong></div></div><div className="lever-list">{levers.map((lever,index)=><div key={lever.name}><b>{index+1}</b><span><em>{lever.group}</em>{lever.name}<small>{lever.action}</small></span><strong>{formatMoney(lever.impact)}</strong></div>)}</div><div className="warning-strip"><Target size={17}/><span>절약액은 실제로 투자 계좌로 옮겨야 자산 증가로 이어집니다. 월급 증가·성과급·절약액을 소비계좌에 남겨 두지 않고 자동이체하는 실행계획까지 정해 주세요.</span></div><LegalDisclaimer/></section></div>;
}
